[package]
name = "memory"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nekoui-config.workspace = true
nekoui-domain.workspace = true

anyhow.workspace = true
chrono.workspace = true
dashmap.workspace = true
serde_json.workspace = true
tracing.workspace = true