[package]
name = "wizard"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nekoui-config.workspace = true

anyhow.workspace = true
dialoguer.workspace = true
tracing.workspace = true
colored.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
