CREATE TABLE IF NOT EXISTS refresh_tokens
(
    id INTEGER PRIMARY KEY NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    token_hash TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)