[package]
name = "agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nekoui-config.workspace = true
nekoui-domain.workspace = true
nekoui-memory.workspace = true
nekoui-telemetry.workspace = true

anyhow.workspace = true
chrono.workspace = true
dashmap.workspace = true
derive_builder.workspace = true
rig.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
serde = { version = "1.0.228", features = ["derive"] }