[package]
name = "nekoui-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
dashmap.workspace = true
nekoui-config.workspace = true
nekoui-domain.workspace = true
nekoui-infra.workspace = true
nekoui-memory.workspace = true
rig.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-retry.workspace = true
tracing.workspace = true
