[package]
name = "nekoui-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
nekoui-agent.workspace = true
nekoui-config.workspace = true
nekoui-infra.workspace = true
nekoui-memory.workspace = true
colored.workspace = true
dialoguer.workspace = true
indicatif.workspace = true
nekoui-setup.workspace = true
tokio.workspace = true
tracing.workspace = true