# For Windows users. If you are linux or macOS user, please delete this line.
set shell := ["powershell.exe", "-c"]

help:
    just -l

neko *args:
    cargo run -p nekoui -- {{args}}

fmt:
    cargo +nightly fmt --all