# For Windows users. If you are linux or macOS user, please delete this line.
set shell := ["powershell.exe", "-c"]

help:
    just -l

neko *args:
    cargo run -p nekoui -- {{args}}

fmt:
    cargo +nightly fmt --all

migrate-add name:
    sqlx migrate add {{name}} --source ./src/repositories/sqlite/migrations

migrate-run:
    sqlx migrate run --source ./src/repositories/sqlite/migrations --database-url "sqlite:./../nekoui.db"

db-create:
    sqlx db create --database-url "sqlite:./../nekoui.db"

db-reset:
    sqlx db reset --source ./src/repositories/sqlite/migrations --database-url "sqlite:./../nekoui.db"