[package]
name = "nekoui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nekoui-agent.workspace = true
nekoui-api-server.workspace = true
nekoui-config.workspace = true
nekoui-telemetry.workspace = true
nekoui-wizard.workspace = true

anyhow.workspace = true
clap.workspace = true
dialoguer.workspace = true
tokio.workspace = true
tracing.workspace = true